# Main configuration root.
root = "."
tmp_dir = "tmp"

[build]
# Command to build your application.
cmd = "go build -o ./tmp/main cmd/server/main.go"
# The binary that Air will run.
bin = "tmp/main"
# Folders to watch for changes.
include_ext = ["go", "tpl", "tmpl", "html"]
# Folders to ignore.
exclude_dir = ["assets", "tmp", "vendor", "generated"]

[log]
# Show log time.
time = true

[misc]
# Delete tmp folder on exit.
clean_on_exit = true